# Docker-compose.yml file for exercise 2.4

version: '3'

services:
        applicationBackend:
            image: example-backend
            build: ./material-applications/example-backend
            environment:
                REDIS_HOST: redis
            ports:
                - 8080:8080
        applicationFrontend:
            image: example-frontend
            build: ./material-applications/example-frontend
            ports:
                - 5000:5000
        redis:
            image: redis
            restart: unless-stopped