# Docker-compose.yml file for exercise 2.6


                                                                   
version: '3'

services:
        applicationBackend:
            image: example-backend
            build: ./material-applications/example-backend
            environment:
                REDIS_HOST: redis

                POSTGRES_HOST: postgres
               
                POSTGRES_DATABASE: postgres

                POSTGRES_USER: postgres
                
                POSTGRES_PASSWORD: postgres

            depends_on:
                - redis
                - postgres

            ports:
                - 8080:8080

        applicationFrontend:
            image: example-frontend
            build: ./material-applications/example-frontend
            ports:
                - 5000:5000

        postgres:
            container_name: postgres
            image: postgres
            environment:
              
                POSTGRES_HOST: postgres
               
                POSTGRES_DATABASE: postgres

                POSTGRES_USER: postgres
                POSTGRES_PASSWORD: postgres
                
        redis:
            image: redis
            restart: unless-stopped