# Docker-compose.yml file for exercise 2.6
                                                 
version: '3'

services:
        applicationBackend:
            image: example-backend
            build: ./material-applications/example-backend
            environment:
                REDIS_HOST: redis

                POSTGRES_HOST: postgresHost
               
                POSTGRES_DATABASE: postgresDB

                POSTGRES_USER: user1234
                
                POSTGRES_PASSWORD: user1234

            depends_on:
                - redis
                - postgres

            ports:
                - 8080:8080

        applicationFrontend:
            image: example-frontend
            build: ./material-applications/example-frontend
            ports:
                - 5000:5000

        postgres:
        
            container_name: postgres

            image: postgres

            environment:
              
                POSTGRES_HOST: postgresHost
               
                POSTGRES_DATABASE: postgresDB

                POSTGRES_USER: user1234

                POSTGRES_PASSWORD: user1234
                
        redis:

            image: redis

            restart: unless-stopped